apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcguildlink-data
spec:
  accessModes: [ReadWriteOnce]
  {{- if .Values.mcguildlink.sqlite.storageClassName }}
  storageClassName: {{ .Values.mcguildlink.sqlite.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mcguildlink.sqlite.storageSize }}