apiVersion: v1
kind: Service
metadata:
  name: mcguildlink-minecraft
spec:
  type: LoadBalancer
  selector: { app.kubernetes.io/name: mcguildlink }
  ports:
    - name: minecraft
      port: {{ .Values.mcguildlink.minecraft.port }}
      targetPort: minecraft
      protocol: TCP