{{- if .Values.publicApi.image.tag }}
apiVersion: v1
kind: Service
metadata:
  name: public-api
spec:
  type: ClusterIP
  selector: { app.kubernetes.io/name: public-api }
  ports:
    - { name: http, port: {{ .Values.publicApi.port }}, targetPort: http }
{{- end }}
