bot:
  image:
    repository: localhost/anvilsaba/bot
    tag: test

cloudflared:
  replicas: 0

mcLinkServer:
  serviceType: ClusterIP
  image:
    repository: localhost/anvilsaba/mc-link-server
    tag: test

publicApi:
  image:
    repository: localhost/anvilsaba/public-api
    tag: test
